version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    ports:
      - "8080:8080"
    volumes:
      - ./Miel/db.sqlite3:/app/db.sqlite3   
      - ./Miel/static:/app/static           
      - ./Miel/media:/app/media 
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    restart: on-failure:5
