# Generated by Django 5.1.3 on 2024-12-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_customuser_patronymic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Patronymic',
            new_name='patronymic',
        ),
    ]
