# Generated by Django 5.1.3 on 2024-12-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_supervisor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='department',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Подразделение'),
        ),
    ]
