# Generated by Django 5.1.3 on 2024-12-18 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_alter_supervisor_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='is_active',
            new_name='is_archive',
        ),
        migrations.CreateModel(
            name='ChatLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'Whatsapp')], max_length=16, verbose_name='Платформа')),
                ('link', models.CharField(max_length=512, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в избранное')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Стала неактивной')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активная ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
