# Generated by Django 5.1.3 on 2025-01-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_alter_candidate_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/users/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/candidates/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
