# Generated by Django 5.1.3 on 2025-01-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_customuser_photo_alter_candidate_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
