# Generated by Django 5.1.3 on 2025-01-21 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_office_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date_complete',
            new_name='complete_at',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='date_update',
            new_name='update_at',
        ),
        migrations.AddField(
            model_name='office',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
