# Generated by Django 5.1.3 on 2025-01-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_rename_date_complete_todo_complete_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlink',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(max_length=32, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='country',
            field=models.CharField(default='Россия', max_length=32, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='образование'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='в архиве'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='свободен'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=16, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='patronymic',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/candidates/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='резюме'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='surname',
            field=models.CharField(max_length=64, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обнавлён'),
        ),
        migrations.AlterField(
            model_name='chatlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='добавлена'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='отправлено'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('invited', 'Приглашён'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='invited', max_length=50, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='office',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cause',
            field=models.CharField(max_length=128, verbose_name='причина'),
        ),
    ]
