# Generated by Django 5.1.3 on 2025-01-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_chatlink_is_active_alter_candidate_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlink',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
    ]
