# Generated by Django 5.1.3 on 2025-02-09 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_alter_chatlink_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waited', 'ожидание'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='waited', max_length=16, verbose_name='статус')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.office', verbose_name='оффис')),
            ],
            options={
                'verbose_name': 'Запросы',
                'verbose_name_plural': 'запрос',
            },
        ),
    ]
