# Generated by Django 5.1.3 on 2025-02-09 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_quotarequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotarequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='созданно'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotarequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
    ]
