# Generated by Django 5.1.3 on 2025-02-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_quotarequest_created_at_quotarequest_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotarequest',
            options={'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
    ]
