# Generated by Django 5.1.3 on 2025-03-31 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_alter_quotarequest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='basic_legal_course',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='completed_objects',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='course_mortgage',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='course_rieltor_join',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='course_taxation',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлён'),
        ),
        migrations.AlterField(
            model_name='quotarequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.CreateModel(
            name='CandidateAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Индивидуальное количество')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.achievement')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.candidate')),
            ],
            options={
                'verbose_name': 'Кандидат-Достижение',
                'verbose_name_plural': 'Кандидат-Достижения',
                'unique_together': {('candidate', 'achievement')},
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_achievements',
            field=models.ManyToManyField(blank=True, related_name='candidate_achievements', to='hr.candidateachievement'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='candidates', to='hr.course'),
        ),
    ]
