# Generated by Django 5.1.3 on 2025-04-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_achievement_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='agreement',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='телефон'),
        ),
    ]
