# Generated by Django 5.1.3 on 2025-04-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_candidate_agreement_alter_candidate_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='agreement',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Согласие на ОПД'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('invited', 'Приглашён'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('self_rejected', 'Отказ Кандидата')], default='invited', max_length=50, verbose_name='статус'),
        ),
    ]
