# Generated by Django 5.1.3 on 2024-12-10 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_todo_date_complete_todo_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.office', verbose_name='Офис'),
        ),
    ]
