# Generated by Django 5.1.3 on 2024-12-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_supervisor_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Patronymic',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество'),
        ),
    ]
